# Experiment configurations for adversarial attacks

#llava-hf/llava-1.5-7b-hf
#Salesforce/blip2-opt-2.7b
model:
  name: "Salesforce/blip2-opt-2.7b"  # or Salesforce/blip2-opt-2.7b or Salesforce/blip-image-captioning-large or llava-hf/llava-1.5-7b-hf
  device: "cuda"
  single_sentence: true
  max_length: 25
  prompt: "Describe the image in one concise sentence."

data:
  root: "data/coco2017"
  split: "val2017"
  max_images: 1000
  batch_size: 16  # Process 4 images simultaneously

# Image saving configuration
save_images:
  enabled: true      # Set to false to disable image saving entirely
  max_count: 10      # Maximum number of image pairs to save (null for all)

wandb:
  project: "adversarial-blip-attacks"
  entity: null  # Set your wandb username/team here
  tags: ["adversarial", "blip", "image-captioning"]

# Experiment definitions
experiments:
  baseline:
    type: "baseline"
    output_file: "eval/baseline_1000.jsonl"
    
  fgsm_eps4:
    type: "attack"
    attack: "fgsm"
    epsilon: "4/255"
    output_file: "eval/fgsm_eps4_255_1000.jsonl"
    save_dir: "runs/fgsm_eps4_255_1000"
    
  fgsm_eps8:
    type: "attack"
    attack: "fgsm"
    epsilon: "8/255"
    output_file: "eval/fgsm_eps8_255_1000.jsonl"
    save_dir: "runs/fgsm_eps8_255_1000"
    
  pgd_eps4:
    type: "attack"
    attack: "pgd"
    epsilon: "4/255"
    alpha: "1/255"
    steps: 10
    output_file: "eval/pgd_s10_a1_255_eps4_255_1000.jsonl"
    save_dir: "runs/pgd_eps4_255_1000"
    
  pgd_eps8:
    type: "attack"
    attack: "pgd"
    epsilon: "8/255"
    alpha: "1/255"
    steps: 10
    output_file: "eval/pgd_s10_a1_255_eps8_255_1000.jsonl"
    save_dir: "runs/pgd_eps8_255_1000"

  veattack_eps6:
    type: "attack"
    attack: "veattack"
    epsilon: "6/255"
    alpha: "1/255"
    steps: 10
    ve_mode: "max"
    ve_momentum: 0.9
    output_file: "eval/veattack_s10_a1_255_eps6_255_1000.jsonl"
    save_dir: "runs/veattack_eps6_255_1000"

  veattack_eps8:
    type: "attack"
    attack: "veattack"
    epsilon: "8/255"
    alpha: "1/255"
    steps: 10
    ve_mode: "max"
    ve_momentum: 0.9
    output_file: "eval/veattack_s10_a1_255_eps8_255_1000.jsonl"
    save_dir: "runs/veattack_eps8_255_1000"
