# Higher-impact / efficiency-focused adversarial attack experiments
model:
  name: "Salesforce/blip2-opt-2.7b"  # or Salesforce/blip2-opt-2.7b or Salesforce/blip-image-captioning-large
  device: "cuda"
  single_sentence: true
  max_length: 25
  prompt: "Describe the image in one concise sentence."

data:
  root: "data/coco2017"
  split: "val2017"
  max_images: 1000
  batch_size: 16

# Image saving configuration (store *_orig.png / *_adv.png pairs)
save_images:
  enabled: true
  max_count: 15

wandb:
  project: "adversarial-blip2-attacks-high-impact"
  entity: null
  tags: ["adversarial", "blip2", "image-captioning", "high-impact"]

experiments:
  baseline:
    type: "baseline"
    output_file: "eval/baseline_1000.jsonl"

  # FGSM with higher eps for stronger, fast single-step attacks
  # Rationale: single-step attacks scale with eps; useful to probe the
  # strength/quality curve quickly at moderate-to-high bounds.
  fgsm_eps6:
    type: "attack"
    attack: "fgsm"
    epsilon: "6/255"
    output_file: "eval/fgsm_eps6_255_1000.jsonl"
    save_dir: "runs/fgsm_eps6_255_1000"

  fgsm_eps10:
    type: "attack"
    attack: "fgsm"
    epsilon: "10/255"
    output_file: "eval/fgsm_eps10_255_1000.jsonl"
    save_dir: "runs/fgsm_eps10_255_1000"

  # PGD variants to explore efficiency vs strength at moderate-to-high eps
  # Keep two effective PGD variants only
  pgd_eps8_s10_a2:
    type: "attack"
    attack: "pgd"
    epsilon: "8/255"
    alpha: "2/255"
    steps: 10
    output_file: "eval/pgd_s10_a2_255_eps8_255_1000.jsonl"
    save_dir: "runs/pgd_eps8_s10_a2_255_1000"

  # Stronger PGD: more steps while staying in same eps bound
  # Rationale: improved optimization may yield stronger caption degradation
  # at the same distortion limit; check impact on LPIPS/SSIM/PSNR.
  pgd_eps10_s20_a2:
    type: "attack"
    attack: "pgd"
    epsilon: "10/255"
    alpha: "2/255"
    steps: 20
    output_file: "eval/pgd_s20_a2_255_eps10_255_1000.jsonl"
    save_dir: "runs/pgd_eps10_s20_a2_255_1000"

  # Add VEAttack (velocity-enhanced) high-impact variants (2 configs)
  veattack_eps8:
    type: "attack"
    attack: "veattack"
    epsilon: "8/255"
    alpha: "2/255"
    steps: 10
    ve_mode: "max"
    ve_momentum: 0.9
    output_file: "eval/veattack_s10_a2_255_eps8_255_1000.jsonl"
    save_dir: "runs/veattack_eps8_s10_a2_255_1000"

  veattack_eps10:
    type: "attack"
    attack: "veattack"
    epsilon: "10/255"
    alpha: "2/255"
    steps: 10
    ve_mode: "max"
    ve_momentum: 0.9
    output_file: "eval/veattack_s10_a2_255_eps10_255_1000.jsonl"
    save_dir: "runs/veattack_eps10_s10_a2_255_1000"
